#!/bin/bash

#SBATCH --job-name=createenv     # Job name
#SBATCH --output=job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=2        # Schedule one core
#SBATCH --time=01:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge        # Run on either the Red or Brown queue

module load Anaconda3/2025.06-1                         # specify anaconda version
module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1        # CUDA/12.1.1 included here, no need to load separately
module load CUDA/12.1.1 || true

export TMPDIR=/home/anaf/tmp

conda create -n sparse_threegs python=3.10                      # or source create; which python version?
source activate sparse_threegs                                  # to install further pkgs activate env or specify env in install line
conda install --quiet --yes plyfile tqdm pip wheel setuptools   # conda instead of pip is faster on hpc
pip install opencv-python joblib                                # for video/image IO and some dataset prep scripts

# Install from submodules (this must run inside the repo folder)
cd ~/sparse-3dgs/gaussian-splatting

pip install submodules/diff-gaussian-rasterization
pip install submodules/simple-knn
pip install submodules/fused-ssim

echo "Environment created successfully."
# Show what got built/linked
python -c "import sys, pkgutil; print('PYTHON:', sys.executable); print(sorted([m.name for m in pkgutil.iter_modules() if m.name in ('diff_gaussian_rasterization','simple_knn','fused_ssim')]))"
