#!/bin/bash

#SBATCH --job-name=env3dgs2           # Job name
#SBATCH --output=env3dgs2.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --error=env3dgs2.%j.err      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=4              # Schedule one core
#SBATCH --time=03:00:00                # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=acltr           # Run on either the Red or Brown queue
#SBATCH --gres=gpu:1                    # needed for submodule build

set -e

module load Anaconda3/2025.06-1         
module load CUDA/12.1.1                 # needed for nvcc?

export CONDA_PKGS_DIRS=/home/anaf/anaconda3-2025/cache # needed?

/opt/itu/easybuild/software/Anaconda3/2025.06-1/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
/opt/itu/easybuild/software/Anaconda3/2025.06-1/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

source /opt/itu/easybuild/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh
conda env create -f /home/anaf/sparse-3dgs/backup-iter5.yml -p /home/anaf/anaconda3-2025/envs/sparse-3dgs2