#!/bin/bash

#SBATCH --job-name=createenv           # Job name
#SBATCH --output=createenv.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=2              # Schedule one core
#SBATCH --time=01:00:00                # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge           # Run on either the Red or Brown queue

set -e
set -x

module load Anaconda3/2025.06-1                         # specify anaconda version
# module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1        # CUDA/12.1.1 included here, no need to load separately
# module load CUDA/12.1.1 || true                         # load anyway in case not true, copilot suggest

export CONDA_PKGS_DIRS=/home/anaf/anaconda3-2025/cache

# Create environment using the conda binary
/opt/itu/easybuild/software/Anaconda3/2025.06-1/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
/opt/itu/easybuild/software/Anaconda3/2025.06-1/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
/opt/itu/easybuild/software/Anaconda3/2025.06-1/bin/conda create -y -p /home/anaf/anaconda3-2025/envs/sparse-3dgs python=3.10

# Load the conda shell function (required in batch jobs)
source /opt/itu/easybuild/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh

# # Verify module loads in env
# conda activate /home/anaf/anaconda3-2025/envs/sparse-3dgs

# python3 - << 'EOF'
# import torch
# print("Torch version:", torch.__version__)
# print("CUDA available:", torch.cuda.is_available())
# if torch.cuda.is_available():
#     print("GPU name:", torch.cuda.get_device_name(0))
# EOF
