#!/bin/bash

#SBATCH --job-name=evaldb    # Job name
#SBATCH --output=evaldb.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule one core
#SBATCH --time=02:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --nodelist=cn4           # specify node
#SBATCH --partition=acltr        # High performance compute nodes with GPUs
#SBATCH --gres=gpu:v100:4        # If you are using CUDA dependent packages

module load Anaconda3/2025.06-1                         # specify anaconda version
module load CUDA/12.1.1
# module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1        # CUDA/12.1.1 included here, no need to load separately

export TMPDIR=/home/anaf/tmp

# Load the conda shell function (required in batch jobs)
source /opt/itu/easybuild/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh

# activation
conda activate /home/anaf/anaconda3-2025/envs/sparse-3dgs       # to install further pkgs activate env or specify env in install line

# nvidia-smi # only in nvidia machine i think
# python train.py -s ../data/db/playroom/ --eval
python render.py -m <path to trained model> # Generate renderings
python metrics.py -m <path to trained model> # Compute error metrics on renderings