#!/bin/bash

#SBATCH --job-name=getdata      # good to have same name as script for error tracing
#SBATCH --output=dtu_download.out
#SBATCH --nodes=1
#SBATCH --time=24:00:00         # put 4 days at least 24 hours
#SBATCH --partition=scavenge

# Use your own tmp storage
export TMPDIR=/home/anaf/tmp

# Go to dataset directory
cd /home/anaf/sparse-3dgs/data

# Download the DTU Rectified dataset (following DNGaussian, CoR-GS)
wget http://roboimagedata2.compute.dtu.dk/data/MVS/Rectified.zip

# Unzip the archive
unzip Rectified.zip