#!/bin/bash

#SBATCH --job-name=installdeps     # Job name
#SBATCH --output=installdeps.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=2        # Schedule one core
#SBATCH --time=01:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge        # Run on either the Red or Brown queue

module load Anaconda3/2025.06-1                         # specify anaconda version
module load CUDA/12.1.1
# module load PyTorch/2.1.2-foss-2023a-CUDA-12.1.1        # CUDA/12.1.1 included here, no need to load separately

export TMPDIR=/home/anaf/tmp

# Load the conda shell function (required in batch jobs)
source /opt/itu/easybuild/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh

# activation
conda activate /home/anaf/anaconda3-2025/envs/sparse-3dgs       # to install further pkgs activate env or specify env in install line

conda install --yes pytorch==2.1.2 torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
conda install --quiet --yes -c conda-forge plyfile tqdm                        # maybe also: pip wheel setuptools
# pip install opencv-python joblib                              # for video/image IO and some dataset prep scripts

# Install from submodules (this must run inside the repo folder)
cd ~/sparse-3dgs/gaussian-splatting

pip install submodules/diff-gaussian-rasterization
pip install submodules/simple-knn
pip install submodules/fused-ssim

echo "Environment created successfully."
nvidia-smi
# Show what got built/linked
python -c "import sys, pkgutil; print('PYTHON:', sys.executable); print(sorted([m.name for m in pkgutil.iter_modules() if m.name in ('diff_gaussian_rasterization','simple_knn','fused_ssim')]))"

# This is for hpc not hpc3