#!/bin/bash

#SBATCH --job-name=installdeps      # Job name
#SBATCH --output=installdeps.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=2           # Schedule one core
#SBATCH --time=01:00:00             # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge        # Run on either the Red or Brown queue

module load Anaconda3/2025.06-1                         
module load CUDA/12.1.1             # I don't think needed here?

export TMPDIR=/home/anaf/tmp

# Load the conda shell function (required in batch jobs) and activate env
source /opt/itu/easybuild/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh
conda activate /home/anaf/anaconda3-2025/envs/sparse-3dgs       

conda install --quiet --yes -c conda-forge plyfile tqdm         # maybe also: pip wheel setuptools
# pip install opencv-python joblib                              # not done yet; for video/image IO and some dataset prep scripts

pip install --no-cache-dir torch==2.1.2+cu121 \
    torchvision==0.16.2+cu121 \
    torchaudio==2.1.2 \
    --index-url https://download.pytorch.org/whl/cu121

echo "=== Testing PyTorch import ==="
python - << 'EOF'
import torch
print("Torch import OK")
print("Torch version:", torch.__version__)
print("CUDA version:", torch.version.cuda)
EOF

echo "DONE."
#### final version ####