#!/bin/bash

#SBATCH --job-name=trainevaldepthone      
#SBATCH --output=trainevaldepthone.%A_%a.out  # %A master job ID, %a task id
#SBATCH --error=trainevaldepthone.%A_%a.err
#SBATCH --cpus-per-task=4               # Schedule 4 as in Vanilla 3DGS
#SBATCH --partition=scavenge            # needed for rtx6000
#SBATCH --nodelist=cn10                 # closest to A6000 from Vanilla 3DGS
#SBATCH --gres=gpu:rtx6000:1            # Vanilla 3DGS is trained on 1 only
#SBATCH --mem=32G
#SBATCH --time=24:00:00                 # enough if 15 min per train

set -e # terminates if training fails, doesn't proceed with rendering or

module load GCC/12.3.0           
module load CUDA/12.1.1
module load Anaconda3/2025.06-1 

SPARSE=/home/anaf/sparse-3dgs
VGS=$SPARSE/gaussian-splatting
export TMPDIR=/home/anaf/tmp

# Load the conda shell function (required in batch jobs) + activate env
source /opt/itu/easybuild/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh
conda activate /home/anaf/anaconda3-2025/envs/sparse-3dgs  

# args
dataset=$1
scene=$2
sampler=$3
view=$4

echo "Running: $dataset $scene | $view views | $sampler sampler | Id $SLURM_ARRAY_TASK_ID"

output=$VGS/output-depth/${dataset}-${scene}-${sampler}-${view}/

python "$VGS/train.py" \
  -s "$SPARSE/data/$dataset/$scene/" \
  -m "$output" \
  --n_views $view \
  --sampler $sampler \
  --eval \
  --disable_viewer \
  -d "$SPARSE/data/$dataset/$scene/depths" 

# Generate renderings for trained model
python "$VGS/render.py" \
  -m "$output"
 
# Compute error metrics on renderings
python "$VGS/metrics.py" \
  -m "$output"

nvidia-smi 

