#!/bin/bash

#SBATCH --job-name=traindb       # Job name
#SBATCH --output=traindb.%j.out  # Name of output file (%j expands to jobId)
#SBATCH --error=traindb.%j.err
#SBATCH --cpus-per-task=4        # Schedule 4 for 3dgs
#SBATCH --partition=scavenge     # High performance compute nodes with GPUs
#SBATCH --nodelist=cn10          # closest to A6000 from vanilla 3dgs?
#SBATCH --gres=gpu:rtx6000:1     # 3dgs is trained on 1 only
#SBATCH --mem=32G
#SBATCH --time=04:00:00          # 4 hours should be more than enough for train on 1 scene

module load Anaconda3/2025.06-1 
module load CUDA/12.1.1

export TMPDIR=/home/anaf/tmp

# Load the conda shell function (required in batch jobs) + activate env
source /opt/itu/easybuild/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh
conda activate /home/anaf/anaconda3-2025/envs/sparse-3dgs  

python /home/anaf/sparse-3dgs/gaussian-splatting/train.py -s ../data/db/playroom/ --eval

nvidia-smi 