#!/bin/bash

#SBATCH --job-name=trainevaldtuc       # Job name
#SBATCH --output=trainevaldtuc.%j.out  # Name of output file (%j expands to jobId)
#SBATCH --error=trainevaldtuc.%j.err
#SBATCH --cpus-per-task=4              # Schedule 4 for VGS
#SBATCH --partition=scavenge           # High performance compute nodes with GPUs
#SBATCH --nodelist=cn10                 # closest to A6000 from vanilla VGS?
#SBATCH --gres=gpu:rtx6000:1            # VGS is trained on 1 only
#SBATCH --mem=32G
#SBATCH --time=04:00:00                 # 4 hours should be more than enough for train on 1 scene

module load GCC/12.3.0           
module load CUDA/12.1.1
module load Anaconda3/2025.06-1 

SPARSE=/home/anaf/sparse-3dgs
VGS=$SPARSE/gaussian-splatting
export TMPDIR=/home/anaf/tmp

# Load the conda shell function (required in batch jobs) + activate env
source /opt/itu/easybuild/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh
conda activate /home/anaf/anaconda3-2025/envs/sparse-3dgs  

# train model for dtu_corgs train
python $VGS/train.py \
    -s $SPARSE/data/dtu_corgs/scan8/ \
    -m $VGS/output/dtu_corgs/scan8/ \
    --eval

# Generate renderings for trained model
python $VGS/render.py \
    -m $VGS/output/dtu_corgs/scan8/
 
# Compute error metrics on renderings
python $VGS/metrics.py \
    -m $VGS/output/dtu_corgs/scan8/

nvidia-smi 

### final version ###