#!/bin/bash

#SBATCH --job-name=trainevaltest        # Job name
#SBATCH --output=trainevaltest.%j.out   # Name of output file (%j expands to jobId)
#SBATCH --error=trainevaltest.%j.err
#SBATCH --cpus-per-task=4               # Schedule 4 for VGS
#SBATCH --partition=scavenge            # High performance compute nodes with GPUs
# #SBATCH --gres=gpu:1                  # VGS is trained on 1 only, gres=gpu:rtx6000:1
#SBATCH --nodelist=cn10                 # closest to A6000 from vanilla VGS?
#SBATCH --gres=gpu:rtx6000:1            # VGS is trained on 1 only
#SBATCH --mem=32G
#SBATCH --time=01:00:00                 # 1 hours should be enough for train on 1 scene, trained < 20 min

set -e # terminates if training fails, doesn't proceed with rendering or

module purge
module load GCC/12.3.0        
module load CUDA/12.1.1
module load Anaconda3/2025.06-1 

SPARSE=/home/anaf/sparse-3dgs
VGS=$SPARSE/gaussian-splatting
export TMPDIR=/home/anaf/tmp

# Load the conda shell function (required in batch jobs) + activate env
source /opt/itu/easybuild/software/Anaconda3/2025.06-1/etc/profile.d/conda.sh
conda activate /home/anaf/anaconda3-2025/envs/sparse-3dgs  

# change into project root, for hard-coded test March 20th
cd $SPARSE  

sampler="baseline"
view=9
output=$VGS/output-test/dtu-scan8-$sampler-$view-norm-1/

# train model for db playroom
python $VGS/train.py \
    -s $SPARSE/data/dtu/scan8/ \
    -m $output \
    --n_views $view \
    --sampler $sampler \
    --eval \
    --disable_viewer
    # -d "$$SPARSE/data/$dataset/$scene/depths" \

# # Generate renderings for trained model
# python $VGS/render.py \
#     -m $output
 
# # Compute error metrics on renderings
# python $VGS/metrics.py \
#     -m $output

# nvidia-smi 

### final version ###